version: '3.7'

services:
  searxng:
    container_name: searxng
    image: searxng/searxng/:latest
#     networks:
#       - searxng
    ports:
     - 8080:8080
    volumes:
      - home/ubuntu/searxng:/etc/searxng
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
#     logging:
#       driver: "json-file"
#       options:
#         max-size: "1m"
#         max-file: "1"

#   caddy:
#     container_name: caddy
#     image: caddy:2-alpine
#     network_mode: host
#     volumes:
#       - home/ubuntu/searxng/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
#       - home/ubuntu/searxng/caddy/caddy-data:/data:rw
#       - home/ubuntu/searxng/caddy/caddy-config:/config:rw
#     environment:
#       - SEARXNG_HOSTNAME=${SEARXNG_HOSTNAME:-http://localhost:80}
#       - SEARXNG_TLS=${LETSENCRYPT_EMAIL:-internal}
#     cap_drop:
#       - ALL
#     cap_add:
#       - NET_BIND_SERVICE
#       - DAC_OVERRIDE

#   redis:
#     container_name: redis
#     image: redis:alpine
#     command: redis-server --save "" --appendonly "no"
#     networks:
#       - searxng
#     tmpfs:
#       - /var/lib/redis
#     cap_drop:
#       - ALL
#     cap_add:
#       - SETGID
#       - SETUID
#       - DAC_OVERRIDE


# networks:
#   searxng:
#     ipam:
#       driver: default

volumes:
  caddy-data:
  caddy-config:
